name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy pylint

      - name: Run Black formatter check
        run: black --check functions/ tests/

      - name: Run flake8
        run: flake8 functions/ tests/ --max-line-length=100 --ignore=E203,W503

      - name: Run pylint
        run: pylint functions/iam_monitor/ --disable=C0111,R0903

      - name: Run mypy type checking
        run: mypy functions/iam_monitor/ --ignore-missing-imports

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r functions/iam_monitor/requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/ -v --cov=functions/iam_monitor --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit

      - name: Run safety check (dependencies)
        run: |
          pip install -r requirements.txt
          pip install -r functions/iam_monitor/requirements.txt
          safety check --json

      - name: Run Bandit (code security)
        run: bandit -r functions/iam_monitor/ -f json -o bandit-report.json || true

      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json

  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Run tfsec (Terraform security scan)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/
          soft_fail: true

  build:
    name: Build Function Package
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd functions/iam_monitor
          pip install -r requirements.txt -t .

      - name: Create deployment package
        run: |
          cd functions/iam_monitor
          zip -r ../../function-source.zip . -x "*.pyc" -x "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: function-source
          path: function-source.zip
          retention-days: 30

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, terraform]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGING }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Download function artifact
        uses: actions/download-artifact@v3
        with:
          name: function-source

      - name: Upload to GCS
        run: |
          gsutil cp function-source.zip gs://${{ secrets.GCP_PROJECT_ID }}-function-source/

      - name: Deploy Terraform
        run: |
          cd terraform
          terraform init
          terraform workspace select staging || terraform workspace new staging
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="environment=staging"

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy iam-immune-system-staging \
            --gen2 \
            --runtime=python311 \
            --region=us-central1 \
            --source=gs://${{ secrets.GCP_PROJECT_ID }}-function-source/function-source.zip \
            --entry-point=handle_iam_event \
            --trigger-topic=iam-events

      - name: Run smoke tests
        run: |
          # Test function health endpoint
          FUNCTION_URL=$(gcloud functions describe iam-immune-system-staging --gen2 --region=us-central1 --format="value(serviceConfig.uri)")
          curl -f $FUNCTION_URL/health || exit 1

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, terraform]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://console.cloud.google.com/functions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Download function artifact
        uses: actions/download-artifact@v3
        with:
          name: function-source

      - name: Upload to GCS
        run: |
          gsutil cp function-source.zip gs://${{ secrets.GCP_PROJECT_ID }}-function-source/

      - name: Deploy Terraform
        run: |
          cd terraform
          terraform init
          terraform workspace select production || terraform workspace new production
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="environment=production"

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy iam-immune-system \
            --gen2 \
            --runtime=python311 \
            --region=us-central1 \
            --source=gs://${{ secrets.GCP_PROJECT_ID }}-function-source/function-source.zip \
            --entry-point=handle_iam_event \
            --trigger-topic=iam-events

      - name: Run smoke tests
        run: |
          # Test function health endpoint
          FUNCTION_URL=$(gcloud functions describe iam-immune-system --gen2 --region=us-central1 --format="value(serviceConfig.uri)")
          curl -f $FUNCTION_URL/health || exit 1

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  notify:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [lint, test, security, terraform, build]
    if: failure()
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'CI Pipeline Failed!'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
